package com.blightstudios.zot.packet;

import java.util.UUID;

/**
 * Protocol constants
 * These are mostly extracted from the ZeTime App
 *
 * @author Moritz Scheve
 */
public interface PConstant {
    byte ACTION_CHECK = 112;
    byte ACTION_CHECK_RESPONSE = -128;
    byte ACTION_SET = 113;
    byte ACTION_SET_RESPONSE = -127;
    int ACTION_SET_RESPONSE_LEN = 8;

    byte BIND_START_NO_UID = 1;
    byte BIND_START_QR_CODE = 2;
    byte BIND_START_SET_UID = 0;

    //region Old 6E protocl
    byte COMMAND_CODE_6E_DEVICE_BATTERY_POWER = 0;
    byte COMMAND_CODE_6E_DEVICE_DEVICE_TYPE = 2;
    byte COMMAND_CODE_6E_DEVICE_FIRMWARE_INFO = 8;

    byte COMMAND_CODE_6E_DEVICE_GET_REMIND = 17;
    byte COMMAND_CODE_6E_DEVICE_GET_SLEEP_COUNT = 21;
    byte COMMAND_CODE_6E_DEVICE_GET_SLEEP_DATA = 19;
    byte COMMAND_CODE_6E_DEVICE_GET_SPORT_COUNT = 18;
    byte COMMAND_CODE_6E_DEVICE_GET_SPORT_DATA = 5;
    byte COMMAND_CODE_6E_DEVICE_GET_USER_INFO = 11;

    byte COMMAND_CODE_6E_DEVICE_INACTIVITY_ALERT = 29;
    byte COMMAND_CODE_6E_DEVICE_RAISE_WAKE = 87;
    byte COMMAND_CODE_6E_DEVICE_SCREEN_BRIGHTNESS_SETTING = 88;
    byte COMMAND_CODE_6E_DEVICE_SOFTWARE_INFO = 9;
    byte COMMAND_CODE_6E_DEVICE_WATCH_ID = 4;

    byte COMMAND_CODE_6E_PHONE_ADD_REMIND = 64;
    byte COMMAND_CODE_6E_PHONE_BATTERY_POWER = 15;
    byte COMMAND_CODE_6E_PHONE_CHANGE_REMIND = 65;
    byte COMMAND_CODE_6E_PHONE_DATETIME = 21;

    byte COMMAND_CODE_6E_PHONE_DELETE_ALL_REMIND = 33;
    byte COMMAND_CODE_6E_PHONE_DELETE_ONE_REMIND = 9;
    byte COMMAND_CODE_6E_PHONE_DELETE_SPORT_SLEEP_DATA = 50;

    byte COMMAND_CODE_6E_PHONE_DEVICE_VERSION = 3;

    byte COMMAND_CODE_6E_PHONE_GET_REMIND = 32;
    byte COMMAND_CODE_6E_PHONE_GET_SLEEP_DATA = 49;
    byte COMMAND_CODE_6E_PHONE_GET_SPORT_DATA = 6;
    byte COMMAND_CODE_6E_PHONE_GET_SPORT_SLEEP_COUNT = 48;
    byte COMMAND_CODE_6E_PHONE_GET_USER_INFO = 20;

    byte COMMAND_CODE_6E_PHONE_INACTIVITY_ALERT = 67;
    byte COMMAND_CODE_6E_PHONE_INIT_SETTING = 19;
    byte COMMAND_CODE_6E_PHONE_INIT_USER_INFO = 18;
    byte COMMAND_CODE_6E_PHONE_MSG_COUNT_PUSH = -77;
    byte COMMAND_CODE_6E_PHONE_RESTORE_FACTORY = 17;
    byte COMMAND_CODE_6E_PHONE_SCREEN_BRIGHTNESS_SETTING = 55;
    byte COMMAND_CODE_6E_PHONE_SEND_INCOME_CALL_NUMBER_NAME = -78;

    byte COMMAND_CODE_6E_PHONE_SET_AUTO_SLEEP = 54;
    byte COMMAND_CODE_6E_PHONE_SET_CALORIES_DISTANCE_GOAL = -94;
    byte COMMAND_CODE_6E_PHONE_SET_STEP_GOAL = 13;
    byte COMMAND_CODE_6E_PHONE_SET_USER_INFO = 12;

    byte COMMAND_CODE_6E_PHONE_SWITCH_SETTING = -76;
    byte COMMAND_CODE_6E_PHONE_TIME_UNIT_DATE_BATTERY = 52;
    byte COMMAND_CODE_6E_PHONE_UPGRADE_MODE = 28;
    byte COMMAND_CODE_6E_PHONE_WATCH_ID = 4;
    //endregion

    // region Command codes
    byte COMMAND_CODE_ANALOG_MODE = 33;
    byte COMMAND_CODE_AUTO_HEART_RATE = 92;
    byte COMMAND_CODE_AUTO_SLEEP = 88;
    byte COMMAND_CODE_BATTERY_POWER = 8;

    byte COMMAND_CODE_BIND_END = -108;
    byte COMMAND_CODE_BIND_START = -109;

    byte COMMAND_CODE_BLOOD_PRESSURE_CHIP_LEARN = 101;

    byte COMMAND_CODE_BRIGHT_SCREEN_TIME = 19;
    byte COMMAND_CODE_BRIGHT_SCREEN_TIME_EX = 37;

    byte COMMAND_CODE_CALENDAR_DAY_VIEW = -103;
    byte COMMAND_CODE_CALENDAR_MONTH_VIEW = -104;

    byte COMMAND_CODE_CALORIES_TYPE = 96;
    byte COMMAND_CODE_CONTROL_DEVICE = 26;

    byte COMMAND_CODE_CUSTOMIZE_COUNT_CRC = -38;
    byte COMMAND_CODE_CUSTOMIZE_REPLY = -37;
    byte COMMAND_CODE_CUSTOMIZE_WATCH_FACE_EX = 30;
    byte COMMAND_CODE_CUSTOMIZE_WATCH_FACE_PRO = 31;
    byte COMMAND_CODE_CUSTOMIZE_WATCH_FACE_SET = 32;

    byte COMMAND_CODE_DATETIME = 4;

    byte COMMAND_CODE_DELETE_BLOOD_PRESSURE_DATA = 99;
    byte COMMAND_CODE_DELETE_HEART_RATE_DATA = 90;
    byte COMMAND_CODE_DELETE_REAL_TIME_SPORT_DATA = 104;
    byte COMMAND_CODE_DELETE_SLEEP_DATA = 85;
    byte COMMAND_CODE_DELETE_SPORT_DATA = 83;

    byte COMMAND_CODE_DEVICE_ACTIVE_RESPONSE = -33;
    byte COMMAND_CODE_DEVICE_DISPLAY_DATA = 87;
    byte COMMAND_CODE_DEVICE_VERSION = 3;

    byte COMMAND_CODE_DO_NOT_DISTURB = 21;
    byte COMMAND_CODE_EMAIL_PUSH = 116;
    byte COMMAND_CODE_EVENT_TIME_INTERVAL = 38;
    byte COMMAND_CODE_FIND_PHONE = -46;
    byte COMMAND_CODE_FLASH_TEST = -9;

    byte COMMAND_CODE_GET_BLOOD_PRESSURE_DATA = 100;
    byte COMMAND_CODE_GET_GPS_DATA = 107;
    byte COMMAND_CODE_GET_HEART_RATE_DATA = 91;
    byte COMMAND_CODE_GET_HEART_RATE_DATA_EX = 97;
    byte COMMAND_CODE_GET_MOOD_DATA = 95;
    byte COMMAND_CODE_GET_REAL_TIME_SPORT_DATA = 103;
    byte COMMAND_CODE_GET_SLEEP_DATA = 86;
    byte COMMAND_CODE_GET_SPORT_DATA = 84;

    byte COMMAND_CODE_GOAL = 80;
    byte COMMAND_CODE_GPS = 106;
    byte COMMAND_CODE_HEART_RATE_ALARM_THRESHOLD = 93;
    byte COMMAND_CODE_INACTIVITY_ALERT = 94;
    byte COMMAND_CODE_INCOME_CALL_RESPONSE = -36;
    byte COMMAND_CODE_LANGUAGE = 11;
    byte COMMAND_CODE_LCD_TEST = -2;
    byte COMMAND_CODE_MACHINE_TIMING = -70;
    byte COMMAND_CODE_MAIN_ALARM_BACKGROUND_COLOR = 17;
    byte COMMAND_CODE_MSG_COUNT_PUSH = 114;
    byte COMMAND_CODE_MUSIC = -48;
    byte COMMAND_CODE_NB_IOT = 40;
    byte COMMAND_CODE_NOTIFICATIONS_TEXT_SIZE = 25;

    byte COMMAND_CODE_OTA_PHOTO = -28;
    byte COMMAND_CODE_OTA_PHOTO_ATTRIBUTE = -27;

    byte COMMAND_CODE_PAY_CARD_NUMBER = -80;
    byte COMMAND_CODE_PAY_MONEY = -79;
    byte COMMAND_CODE_PAY_PASS_THROUGH = -77;
    byte COMMAND_CODE_PAY_RECORD = -78;

    byte COMMAND_CODE_PHONE_CONTACT = -43;
    byte COMMAND_CODE_PHONE_NAME_PUSH = 112;

    byte COMMAND_CODE_POWER_OFF_MODE = 23;
    byte COMMAND_CODE_PRIMARY_SURFACE_DISPLAY_SETTING = 6;
    byte COMMAND_CODE_PROTOCOL_SET = -102;
    byte COMMAND_CODE_REAL_TIME_HEART_RATE = -30;

    byte COMMAND_CODE_REMIND_COUNT = -111;
    byte COMMAND_CODE_REMIND_SETTING = -110;
    byte COMMAND_CODE_REMIND_SETTING_EX_DATE = -107;
    byte COMMAND_CODE_REMIND_SETTING_EX_DATE_SHOCK = -105;
    byte COMMAND_CODE_REMIND_SETTING_EX_DATE_SHOCK_REPEAT = -101;
    byte COMMAND_CODE_REMIND_SETTING_EX_SHOCK = -106;

    byte COMMAND_CODE_RESPONSE = 1;
    byte COMMAND_CODE_RESTORE_FACTORY = 13;
    byte COMMAND_CODE_SCHEDULE_PUSH = 117;
    byte COMMAND_CODE_SCREEN_BRIGHTNESS_SETTING = 7;
    byte COMMAND_CODE_SEND_SOS = -39;
    byte COMMAND_CODE_SEND_TRANSPARENT_COMMAND = -29;
    byte COMMAND_CODE_SENSOR_TEST = -4;

    byte COMMAND_CODE_SHOCK_MODE = 10;
    byte COMMAND_CODE_SHOCK_STRENGTH = 16;
    byte COMMAND_CODE_SHOCK_TEST = -6;

    byte COMMAND_CODE_SMS_PUSH = 113;
    byte COMMAND_CODE_SMS_REPLY = -35;
    byte COMMAND_CODE_SMS_REPLY_CONTENT = -34;

    byte COMMAND_CODE_SNOOZE = 20;

    byte COMMAND_CODE_SOCIAL_EX_PUSH = 118;
    byte COMMAND_CODE_SOCIAL_PUSH = 115;
    byte COMMAND_CODE_SOCIAL_REPLY = -26;

    byte COMMAND_CODE_SPECIFIC_APPLICATION_UNIT = 39;
    byte COMMAND_CODE_SPORT_SLEEP_MODE = 81;
    byte COMMAND_CODE_SWITCH_SETTING = -112;
    byte COMMAND_CODE_TAKE_PHOTO = -47;
    byte COMMAND_CODE_THREE_AXES_SENSOR = -43;

    byte COMMAND_CODE_TIME_SURFACE_SETTING = 5;
    byte COMMAND_CODE_TIME_ZONE = 24;

    byte COMMAND_CODE_TOTAL_BLOOD_PRESSURE_COUNT = 98;
    byte COMMAND_CODE_TOTAL_HEART_RATE_COUNT = 89;
    byte COMMAND_CODE_TOTAL_REAL_TIME_SPORT_DATA_COUNT = 102;
    byte COMMAND_CODE_TOTAL_SPORT_SLEEP_COUNT = 82;

    byte COMMAND_CODE_TOUCH_TEST = -5;
    byte COMMAND_CODE_TRAN_SPEED = 22;
    byte COMMAND_CODE_UNIT = 12;
    byte COMMAND_CODE_UPGRADE_MODE = 14;
    byte COMMAND_CODE_UPLOAD_NFC = -40;
    byte COMMAND_CODE_USAGE_HABITS = 49;

    byte COMMAND_CODE_USER_INFO = 48;
    byte COMMAND_CODE_USER_NAME = 50;

    byte COMMAND_CODE_VOLUME = 9;

    byte COMMAND_CODE_WATCH_ID = 2;
    byte COMMAND_CODE_WATCH_MOVE_KEEP = -72;
    byte COMMAND_CODE_WATCH_MOVE_KEEP_OLD = -40;
    byte COMMAND_CODE_WATCH_MOVE_ONE = -74;
    byte COMMAND_CODE_WATCH_MOVE_ONE_OLD = -42;
    byte COMMAND_CODE_WATCH_POINTER_POSITION = -17;

    byte COMMAND_CODE_WEATHER_PUSH = 119;
    byte COMMAND_CODE_WEATHER_SETTING = 34;

    byte COMMAND_CODE_WORK_MODE = 18;
    byte COMMAND_CODE_WRITE_WATCH_ID = -1;
    // endregion

    byte CONTROL_DEVICE_SET_AVI_APPLICATION_CLOSE = 8;
    byte CONTROL_DEVICE_SET_AVI_APPLICATION_OPEN = 7;

    byte CONTROL_DEVICE_SET_ENTER_FLIGHT_MODE = 2;
    byte CONTROL_DEVICE_SET_JUMP_REAL_TIME_HEART_RATE = 3;
    byte CONTROL_DEVICE_SET_LIGHT_SCREEN = 0;
    byte CONTROL_DEVICE_SET_SHUT_DOWN = 1;

    byte CONTROL_DEVICE_SET_START_MACHINE_TIMING_HOUR = 4;
    byte CONTROL_DEVICE_SET_START_MACHINE_TIMING_MINUTE = 5;

    byte CONTROL_DEVICE_GET_TRACKING = 0;
    byte CONTROL_DEVICE_SET_TRACKING_ALLOW = 10;
    byte CONTROL_DEVICE_SET_TRACKING_FORBID = 9;

    int CUSTOMIZE_REPLY_ADD = 0;
    int CUSTOMIZE_REPLY_CHG = 1;
    int CUSTOMIZE_REPLY_DEL = 2;

    byte EMAIL_PUSH_TYPE_ADDRESS = 0;
    byte EMAIL_PUSH_TYPE_CONTENT = 1;
    byte EMAIL_PUSH_TYPE_DATETIME = 2;

    byte EVENT_TIME_INTERVAL_TYPE_DRINK_WATER = 0;

    /**
     * The starting bytes which are at the start of every packet
     */
    byte FLAG_START = 111;

    /**
     * The starting bytes which are used for the old 6E protocol version
     */
    byte FLAG_START_OLD = 110;

    /**
     * The ending bytes which are at the end of every packet
     */
    byte FLAG_END = -113;

    byte GOAL_TYPE_6E_CALORIES = -127;
    byte GOAL_TYPE_6E_DISTANCE = -126;
    byte GOAL_TYPE_6E_SLEEP = -122;
    byte GOAL_TYPE_6E_STEP = -123;

    byte GOAL_TYPE_CALORIE = 1;
    byte GOAL_TYPE_DISTANCE = 2;
    byte GOAL_TYPE_SLEEP = 3;
    byte GOAL_TYPE_SPORT_TIME = 4;
    byte GOAL_TYPE_STEP = 0;

    int INTERFACE_DISPLAY_BANKCARD = 7;
    int INTERFACE_DISPLAY_CALORIE = 4;
    int INTERFACE_DISPLAY_CITYCARD = 6;
    int INTERFACE_DISPLAY_DISTANCE = 3;
    int INTERFACE_DISPLAY_SLEEP = 5;
    int INTERFACE_DISPLAY_STEP = 2;
    int INTERFACE_DISPLAY_TIME = 1;

    int LEN_128 = 128;
    int LEN_240 = 240;
    int LEN_90 = 90;

    byte MSG_PUSH_TYPE_CALENDAR = 4;
    byte MSG_PUSH_TYPE_EMAIL = 3;
    byte MSG_PUSH_TYPE_FACEBOOK = 12;
    byte MSG_PUSH_TYPE_GMAIL = 14;
    byte MSG_PUSH_TYPE_HANGOUTS = 13;
    byte MSG_PUSH_TYPE_INCOME_CALL = 5;
    byte MSG_PUSH_TYPE_INSTAGRAM = 16;
    byte MSG_PUSH_TYPE_LINE = 20;
    byte MSG_PUSH_TYPE_LINKEDIN = 18;
    byte MSG_PUSH_TYPE_MESSENGER = 15;
    byte MSG_PUSH_TYPE_MISS_CALL = 0;
    byte MSG_PUSH_TYPE_OFF_CALL = 6;
    byte MSG_PUSH_TYPE_QQ = 11;
    byte MSG_PUSH_TYPE_SKYPE = 21;
    byte MSG_PUSH_TYPE_SMS = 1;
    byte MSG_PUSH_TYPE_SNAPCHAT = 9;
    byte MSG_PUSH_TYPE_SOCIAL = 2;
    byte MSG_PUSH_TYPE_TWITTER = 17;
    byte MSG_PUSH_TYPE_UBER = 19;
    byte MSG_PUSH_TYPE_VIBER = 8;
    byte MSG_PUSH_TYPE_WECHAT = 7;
    byte MSG_PUSH_TYPE_WHATSAPP = 10;

    byte NB_IOT_GET_CSQ = 2;
    byte NB_IOT_GET_IMEI = 0;
    byte NB_IOT_GET_IMSI = 1;
    byte NB_IOT_SET_CLOSE = 0;
    byte NB_IOT_SET_RESET = 1;

    byte PHONE_NAME_PUSH_TYPE_INCOME_CALL = 0;
    byte PHONE_NAME_PUSH_TYPE_MISS_CALL = 2;
    byte PHONE_NAME_PUSH_TYPE_MISS_CALL_DATETIME = 3;
    byte PHONE_NAME_PUSH_TYPE_REDIAL_CALL = 1;

    byte REMIND_TYPE_AWAKE = 4;
    byte REMIND_TYPE_BILLS = 8;
    byte REMIND_TYPE_CUSTOM = 7;
    byte REMIND_TYPE_DRINK = 2;
    byte REMIND_TYPE_EAT = 0;
    byte REMIND_TYPE_MEDICINE = 1;
    byte REMIND_TYPE_MEETING = 6;
    byte REMIND_TYPE_PERSONNEL = 9;
    byte REMIND_TYPE_SLEEP = 3;
    byte REMIND_TYPE_SPORT = 5;

    byte REMOTE_FIND_PHONE_END = 1;
    byte REMOTE_FIND_PHONE_START = 0;

    byte REMOTE_MUSIC_CHECK_MUSIC_STATE = 0;

    byte REMOTE_MUSIC_SEND_DEVICE_PAUSE = 1;
    byte REMOTE_MUSIC_SEND_DEVICE_PLAY = 0;
    byte REMOTE_MUSIC_SEND_DEVICE_STOP = -1;
    byte REMOTE_MUSIC_SEND_DEVICE_VOLUME = 2;

    byte REMOTE_MUSIC_SET_PHONE_NEXT_SONG = 3;
    byte REMOTE_MUSIC_SET_PHONE_PAUSE = 1;
    byte REMOTE_MUSIC_SET_PHONE_PLAY = 0;
    byte REMOTE_MUSIC_SET_PHONE_PRE_SONG = 2;
    byte REMOTE_MUSIC_SET_PHONE_VOLUME = 4;
    byte REMOTE_MUSIC_SET_PHONE_VOLUME_INCREASE = 5;
    byte REMOTE_MUSIC_SET_PHONE_VOLUME_REDUCE = 6;

    byte REMOTE_RECTIFY_HOUR = 3;
    byte REMOTE_RECTIFY_MIN = 4;

    byte REMOTE_TAKE_PHONE_CONNECT_APP = 2;
    byte REMOTE_TAKE_PHONE_END = 1;
    byte REMOTE_TAKE_PHONE_START = 0;
    byte REMOTE_TAKE_PHONE_SWITCH_ON = 3;

    byte RESPONSE_ERROR = 2;
    byte RESPONSE_FAIL = 1;
    byte RESPONSE_SUCCESS = 0;

    int RESULT_CODE_BLUETOOTH_VAR_NULL = -4;
    int RESULT_CODE_CONTINUE_RECEIVE = 3;
    int RESULT_CODE_CONTINUE_RECEIVE_6E = 6;
    int RESULT_CODE_ERROR = -1;
    int RESULT_CODE_EXCEPTION = -3;
    int RESULT_CODE_FAIL = 1;
    int RESULT_CODE_INDEXS_COMMAND = 4;
    int RESULT_CODE_LARGE_BYTES_ERROR = -2;
    int RESULT_CODE_PROTOCOL_ERROR = 2;
    int RESULT_CODE_RE_SEND = 5;
    int RESULT_CODE_SUCCESS = 0;

    byte SCHEDULE_PUSH_TYPE_CONTENT = 1;
    byte SCHEDULE_PUSH_TYPE_DATETIME = 2;

    int SHOCK_ACTION_ANTI = 0;
    int SHOCK_ACTION_CALENDAR = 7;
    int SHOCK_ACTION_CLOCK = 1;
    int SHOCK_ACTION_EMAIL = 6;
    int SHOCK_ACTION_INCOME_CALL = 2;
    int SHOCK_ACTION_LOW_POWER = 9;
    int SHOCK_ACTION_MISS_CALL = 3;
    int SHOCK_ACTION_SEDENTARY = 8;
    int SHOCK_ACTION_SMS = 4;
    int SHOCK_ACTION_SOCIAL = 5;

    int SHOCK_MODE_ALWAYS_LONG_SHOCK = 6;
    int SHOCK_MODE_ALWAYS_SHOCK_SOUND = 13;
    int SHOCK_MODE_ALWAYS_SHORT_SHOCK = 7;
    int SHOCK_MODE_ALWAYS_SOUND = 11;
    byte SHOCK_MODE_DEFAULT = 2;
    byte SHOCK_MODE_FLIGHT = 1;
    int SHOCK_MODE_INTERVAL_FIVE_LONG_SHOCK = 8;
    int SHOCK_MODE_INTERVAL_LONG_SHORT_SHOCK = 5;
    int SHOCK_MODE_INTERVAL_TWO_LONG_SHOCK = 3;
    int SHOCK_MODE_INTERVAL_TWO_SHORT_SHOCK = 4;
    int SHOCK_MODE_MUTE = 14;
    int SHOCK_MODE_NO_SHOCK = 0;
    int SHOCK_MODE_ONE_SHOCK_SOUND = 12;
    int SHOCK_MODE_SIGNAL_LONG_SHOCK = 1;
    int SHOCK_MODE_SIGNAL_SHORT_SHOCK = 2;
    int SHOCK_MODE_SIGNAL_SOUND = 9;
    int SHOCK_MODE_TWO_SOUND = 10;
    byte SHOCK_MODE_custom = 3;

    byte SMS_PUSH_TYPE_CONTENT = 1;
    byte SMS_PUSH_TYPE_DATETIME = 2;
    byte SMS_PUSH_TYPE_NAME_OR_NUMBER = 0;

    byte SOCIAL_PUSH_TYPE_CONTENT = 1;
    byte SOCIAL_PUSH_TYPE_DATETIME = 2;
    byte SOCIAL_PUSH_TYPE_TITLE = 0;

    int SWITCH_BIT_ANTI = 1;
    int SWITCH_BIT_AUTO_SLEEP = 8;
    int SWITCH_BIT_AUTO_SYNC = 2;
    int SWITCH_BIT_CALENDAR = 512;
    int SWITCH_BIT_CALL = 16;
    int SWITCH_BIT_EMAIL = 256;
    int SWITCH_BIT_GOAL_ACHIEVED = 32768;
    int SWITCH_BIT_HEART_RATE_MONITOR = 262144;
    int SWITCH_BIT_LOW_POWER = 2048;
    int SWITCH_BIT_MISS_CALL = 32;
    int SWITCH_BIT_RAISE_WAKE = 16384;
    int SWITCH_BIT_REAL_HEART_RATE = 65536;
    int SWITCH_BIT_RING = 8192;
    int SWITCH_BIT_SECOND_REMINDER = 4096;
    int SWITCH_BIT_SEDENTARY = 1024;
    int SWITCH_BIT_SLEEP = 4;
    int SWITCH_BIT_SMS = 64;
    int SWITCH_BIT_SOCIAL = 128;
    int SWITCH_BIT_SUPER_ALARM_CLOCK = 131072;
    int SWITCH_BIT_THREE_AXES_SENSOR = 524288;

    byte SWITCH_TYPE_ANTI = 0;
    byte SWITCH_TYPE_AUTO_SLEEP = 3;
    byte SWITCH_TYPE_AUTO_SYNC = 1;
    byte SWITCH_TYPE_CALENDAR = 9;
    byte SWITCH_TYPE_CALL = 4;
    byte SWITCH_TYPE_EMAIL = 8;
    byte SWITCH_TYPE_GOAL_ACHIEVED = 15;
    byte SWITCH_TYPE_HEART_RATE_MONITOR = 18;
    byte SWITCH_TYPE_HRV = 21;
    byte SWITCH_TYPE_LOW_POWER = 11;
    byte SWITCH_TYPE_MISS_CALL = 5;
    byte SWITCH_TYPE_RAISE_WAKE = 14;
    byte SWITCH_TYPE_REAL_HEART_RATE = 16;
    byte SWITCH_TYPE_RING = 13;
    byte SWITCH_TYPE_SECOND_REMINDER = 12;
    byte SWITCH_TYPE_SEDENTARY = 10;
    byte SWITCH_TYPE_SLEEP = 2;
    byte SWITCH_TYPE_SMS = 6;
    byte SWITCH_TYPE_SOCIAL = 7;
    byte SWITCH_TYPE_SUPER_ALARM_CLOCK = 17;
    byte SWITCH_TYPE_THREE_AXES_SENSOR = 19;

    byte TRAN_SPEED_FAST = 3;
    byte TRAN_SPEED_NORMAL = 2;
    byte TRAN_SPEED_SLOW = 1;

    byte USAGE_HABITS_LEFT = 0;
    byte USAGE_HABITS_RIGHT = 1;

    UUID UUID_CHARACTERISTIC_8001 = UUID.fromString("00008001-0000-1000-8000-00805f9b34fb");
    UUID UUID_CHARACTERISTIC_8002 = UUID.fromString("00008002-0000-1000-8000-00805f9b34fb");
    UUID UUID_CHARACTERISTIC_8003 = UUID.fromString("00008003-0000-1000-8000-00805f9b34fb");
    UUID UUID_CHARACTERISTIC_8004 = UUID.fromString("00008004-0000-1000-8000-00805f9b34fb");
    UUID UUID_CHARACTERISTIC_8005 = UUID.fromString("00008005-0000-1000-8000-00805f9b34fb");
    UUID UUID_CHARACTERISTIC_APOLLO_1531 = UUID.fromString("00001531-0000-1000-8000-00805f9b34fb");
    UUID UUID_CHARACTERISTIC_APOLLO_1532 = UUID.fromString("00001532-0000-1000-8000-00805f9b34fb");
    UUID UUID_CHARACTERISTIC_HEART_RATE = UUID.fromString("00002a37-0000-1000-8000-00805f9b34fb");
    UUID UUID_CONFIG_DESCRIPTOR = UUID.fromString("00002902-0000-1000-8000-00805f9b34fb");
    UUID UUID_SERVICE_APOLLO_DFU = UUID.fromString("00001530-0000-1000-8000-00805f9b34fb");
    UUID UUID_SERVICE_BASE = UUID.fromString("00006006-0000-1000-8000-00805f9b34fb");
    UUID UUID_SERVICE_EXTEND = UUID.fromString("00007006-0000-1000-8000-00805f9b34fb");
    UUID UUID_SERVICE_HEART_RATE = UUID.fromString("0000180d-0000-1000-8000-00805f9b34fb");
    byte WORK_MODE_POWER_SAVE = 0;
}